"""Add user_level to UserMapping

Revision ID: e901bbb02edb
Revises: ebca0a22917a
Create Date: 2025-03-18 06:53:28.066550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e901bbb02edb'
down_revision: Union[str, None] = 'ebca0a22917a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mapping', sa.Column('user_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mapping', 'user_level')
    # ### end Alembic commands ###
