"""Added user_mapping table

Revision ID: ebca0a22917a
Revises: 454b3acd0d51
Create Date: 2025-03-17 08:54:52.638974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebca0a22917a'
down_revision: Union[str, None] = '454b3acd0d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('microinvest_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microinvest_user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_mapping_id'), 'user_mapping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mapping_id'), table_name='user_mapping')
    op.drop_table('user_mapping')
    # ### end Alembic commands ###
